### ISSUE TITLE
Notice-Meldungen

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/Design-Luna#4]
stört ja nicht weiter, aber einfach zur Info weil man die manchmal selber nicht bekommt beim Testen:
Notice: Undefined index: label-talk-pl in /proj/websource/docs/RRZEWeb/www.irgendwas.test.rrze.uni-erlangen.de/websource/wp-content/themes/Design-Luna/inc/custom-post-types.php on line 10 
Notice: Undefined index: label-speaker-pl in /proj/websource/docs/RRZEWeb/www.irgendwas.test.rrze.uni-erlangen.de/websource/wp-content/themes/Design-Luna/inc/custom-post-types.php on line 527 
Notice: Undefined index: headerbox-logo in /proj/websource/docs/RRZEWeb/www.irgendwas.test.rrze.uni-erlangen.de/websource/wp-content/themes/Design-Luna/header.php on line 68

**Comment by cassandre** [comment]
Fixed in https://github.com/RRZE-Webteam/Design-Luna/commit/bfff11b035f969b79bfdf737b20346917b6d5128
